host_url: http://jaegerqe-query:16686
tags:
  - master
query:
  - name: 1.last 12 hours limit 100
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 100
      lookback: custom
      start: -12h
      end: 0h

  - name: 1.last 12 hours limit 1000
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 1000
      lookback: custom
      start: -12h
      end: 0h

  - name: 1.last 12 hours limit 2000
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 2000
      lookback: custom
      start: -12h
      end: 0h

  - name: 2.last 24 hours limit 100
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 100
      lookback: custom
      start: -24h
      end: 0h

  - name: 2.last 24 hours limit 1000
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 1000
      lookback: custom
      start: -24h
      end: 0h

  - name: 2.last 24 hours limit 2000
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 2000
      lookback: custom
      start: -24h
      end: 0h

  - name: 3.last 2 days limit 100
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 100
      lookback: custom
      start: -48h
      end: 0h

  - name: 3.last 2 days limit 1000
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 1000
      lookback: custom
      start: -48h
      end: 0h

  - name: 3.last 2 days limit 2000
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 2000
      lookback: custom
      start: -48h
      end: 0h

  - name: 4.last 7 days limit 100
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 100
      lookback: custom
      start: -168h
      end: 0h

  - name: 4.last 7 days limit 1000
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 1000
      lookback: custom
      start: -168h
      end: 0h

  - name: 4.last 7 days limit 2000
    type: search
    repeat_count: 10
    status_code: 200
    query_params:
      service: jaegerperf_generator
      limit: 2000
      lookback: custom
      start: -168h
      end: 0h
